# Generated by Django 4.2.1 on 2024-10-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='achivement_model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('achivement_name', models.CharField(max_length=80)),
                ('achivement_pdf', models.FileField(upload_to='achivement_pdf/')),
                ('provider', models.CharField(max_length=60)),
                ('achivement_year', models.DateField()),
                ('duration', models.DurationField()),
                ('achivement_img', models.ImageField(upload_to='achivement_img/')),
            ],
        ),
    ]
