# Generated by Django 4.2.1 on 2024-10-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sushant1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achivement_model',
            name='achivement_img',
            field=models.ImageField(upload_to='achivement_doc/achivement_img/'),
        ),
    ]
